### ISSUE TITLE
Reconsider using WebSockets

### ISSUE THREAD

**Issue by Geosearchef** [whirlwind-studios/School1#4]
"School1 will be powered by an WebSocket backend"

WebSockets are probably not the best option in this case. When compared to HTTP(s) Request/Response Pattern, they have a really small overhead when sending a lot of messages. (which is useful for a realtime application and enables bidirectional communication)

But as this Application will probably not be transmitting that much Information, Overhead won't be the main problem here in my opinion. (who's interested in a few KBs reduced data usage per day anyways?)
This use case sounds more like it's going to request updates every few minutes. (that's probably way too much)

A way bigger problem, as the main focus will be on mobile platforms anyways, will be the battery life. One request every few minutes, that wakes up the CPU (Android is idle by default, but the CPU can be woken up by events, which consumes a lot of energy if done frequently) and triggers a mobile connection (which draws a lot of energy) is fine.

But if you use WebSockets, you're establishing a permanent TCP connection. TCP has overhead like KeepAlive Packets, which may even be sent every few seconds. In fact, most firewalls will block connections if they haven't seen an outgoing packet in the last 20-30 seconds. As you're not sending lots of data, this idle connection will sit around, do nothing useful, wake up your CPU (consumes energy, android 6+ will even warn about applications frequently waking up the phone while in standby), and trigger a mobile connection (which draws a lot of energy). Multiple times per minute.

Actually, if you want to transmit data in background (updating, alerting about news/new events), then you will have a problem on iOS anyways. The system drops WebSocket connections when switching an App to background. So you will have to reestablish the connection anyways, which removes the whole benefit of using a WebSocket.

I'd suggest just using standard HTTPS Get/Post.

---------------------------------
Quote:
"Fetching Small Amounts of Content Opportunistically

So it seems that this option is only usable for obtaining small amounts of content through HTTP requests (or other network requests), not for the kind of two-way constant communication a websocket would allow you to use. In fact, looking at other related answers, it seems there is indeed no legitimate manner to keep a socket open when the app enters background mode."

Source: https://stackoverflow.com/questions/43853812/prevent-websocket-connection-to-drop-when-entering-background-state-ios-swift

**Comment by Zhyano** [comment]
Okay, at this point I don't agree with you.

Just to be clear: 
School1 will have some minor realtime component, and I don't want to pull in a 3rd party service.

That really renders your arguments in favor of WebSockets, but let's explain my idea behind it:

- Realtime with HTTP
  - Long - Polling. Same problem as with WebSockets, open connection in the background, keepalive and stuff and additionally expensive reconnects
  - Polling. Really expensive for both client and server, as both need to wake up and transmit data every 10-15 minutes at least. And imagine a chat application (the focus will not lay on this component of the app, but it will still be relevant) with a latency of 3 minutes. Horrible!
- WebSockets. There is [no TCP keepalive](https://stackoverflow.com/questions/23238319/websockets-ping-pong-why-not-tcp-keepalive), only application triggered ping-pong packets. Which don't need to be sent at all. Data is only sent if a user changed or added anything (as this is an event which is then sent to related users), which should, as you already said, not happen all that often. And just to remind: Idle TCP connections cost about _nothing_. (I will test this)

---

As per background processes/sockets in iOS: The Hybrid apps aren't meant as normal native apps written with web technologies, they should be a web app compiled for mobile to reduce user friction, by allowing them to use it directly as an app on their phone, not needing to open a browser and load a webpage or something. Particularly the iOS app will be later improved in the future, but at first it should only be capable of handling the base functionality.

>So you will have to reestablish the connection anyways, which removes the whole benefit of using a WebSocket.

Yeah, that's true, but it also has no disadvantage. And it's still capable of real-time action while being inside the app.

And about server side costs: On a Raspberry Pi with 1 GB RAM, and let's say 200 MB reserved for other applications, relying on [a real world benchmark which used 46 GB for 12 millions of connections](https://mrotaru.wordpress.com/2013/10/10/scaling-to-12-million-concurrent-connections-how-migratorydata-did-it/) this would result in a maximum of about 200 thousands of open connections, which should be really really more than enough (although you can expect less connections being feasible in real life, as there are some other components, e.g. router also involved, and benchmarks are just still benchmarks).

>One request every few minutes, that wakes up the CPU

This is also an invalid argument, as School1 will be based on _server-side_ events (unfortunately the backend specification is not yet ready). This means, when anything changes on the server, it sends a message to the client, which may be once a day, or every five seconds, depending on how frequently users are updating anything (like sending text messages or adding a homework).

>who's interested in a few KBs reduced data usage per day anyways?

This is actually an argument against you, as transferred data is (nearly) the only thing that matters when it comes to CPU usage and therefore battery life. And every user has some spare 1MB of RAM, I hope.

---
Hoping for an interesting discussion though (You will probably deny some of my arguments...)

**Comment by Geosearchef** [comment]
I have a test tomorrow, so later on. You're arguments are good, I agree, you could use a websocket, but you should really think this all the way through so you don't encounter any unforseen obstacles. So let's discuss. ;)

**Comment by Zhyano** [comment]
Yeah, actually this is the third backend change in the lifetime of School1, so it's my main objective to make a sophisticated choice. This will be evaluated, especially the background service thing, but currently it _seems_ like a good idea :)

**Comment by Geosearchef** [comment]
Just a few thoughts.
On mobile, connection is often lost, IP address changes, wifi<->mobile switch, OS kills app,.....
All of this interrupts a TCP connection (after timeout).

It's a compromise between realtime and battery usage.
Maybe have a look at Google Cloud Messaging, was specifically implemented for this purpose. https://code.tutsplus.com/tutorials/how-to-get-started-with-push-notifications-on-android--cms-25870
But is this android specific?

**Comment by Zhyano** [comment]
Okay, I must admit, [Firebase](https://firebase.google.com/) is looking interesting...

But in the end, even Firebase Cloud Messaging (which replaced GCM) and Firebase Realtime Database (which is an interesting approach for a backend) [_both_ use WebSockets internally](https://groups.google.com/forum/m/#!topic/firebase-talk/lD91N6Zalfw) too.

I think there is no other, more efficient way to allow realtime updates than Sockets. The most efficient way would be grouping messages from different apps on a single device into groups to prevent many open connections and many small messages, but would in turn create dependencies on that service and destroy the idea of a realtime application.
But well, just read that Firebase is [doing quite such a thing](https://developer.android.com/training/monitoring-device-state/doze-standby.html#using_fcm), it even persists during android doze and is able to group normal priority messages.

I'll have a look at all of these approaches... And do some testing in the future... What do you think?

**Comment by Avothr** [comment]
Wouldn't the backend impact the programming of the webpage too? Just to think outside the box...

**Comment by Geosearchef** [comment]
It would impact everything. But on the webpage, it dosn't matter. It's either on a PC or on a mobile device where the page is killed anyways when switching tab.

**Comment by Zhyano** [comment]
Sure the choice of a backend would impact the actual implementation on all platforms, but the actual result is the same with some tweaking in both solutions.

### Comparison

- Scalability. How easy it is to react (in terms of costs and available hardware) to new requirements, like a changing number of users. Firebase clearly got this point.
- Cost. How expensive a solution is in long, and in short term. In short term my little Raspi definitely wins, and in long term it should also be more money efficient.
- Work and maintenance. Firebase definetely wins here.
- Fun. Depends on frustration when debugging, but a custom solution is probably way more interesting.
- Battery usage. Firebase should also win here, but with some battery-saving logic, the margin wouldn't be too high.
- App size. As Firebase needs a bunch of additional stuff, the App size would grow noticeably. Point for a custom solution.
- Security. As I'm not stupid, nor stubborn, I definitely learned my lessons from my previous approaches, and with the help of this open source community a highly secure app is quite realistic. No point for anyone.

Well, that's a kind of artificial comparison, because it was made to be a draw :)

---
Are there any other parties or points to consider?

**Comment by Zhyano** [comment]
Sure the choice of a backend would impact the actual implementation on all platforms, but the actual result is the same with some tweaking in both solutions.

### Comparison

- Scalability. How easy it is to react (in terms of costs and available hardware) to new requirements, like a changing number of users. Firebase clearly got this point.
- Cost. How expensive a solution is in long, and in short term. In short term my little Raspi definitely wins, and in long term it should also be more money efficient.
- Work and maintenance. Firebase definetely wins here.
- Fun. Depends on frustration when debugging, but a custom solution is probably way more interesting.
- Battery usage. Firebase should also win here, but with some battery-saving logic, the margin wouldn't be too high.
- App size. As Firebase needs a bunch of additional stuff, the App size would grow noticeably. Point for a custom solution.
- Security. As I'm not stupid, nor stubborn, I definitely learned my lessons from my previous approaches, and with the help of this open source community a highly secure app is quite realistic. No point for anyone.

Well, that's a kind of artificial comparison, because it was made to be a draw :)

---
Are there any other parties or points to consider?

**Comment by Zhyano** [comment]
Firebase is locked as backend choice. We'll see, how good it is in practice, but seems promising.
Thanks for your critic again!
